/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import MinimalPrimes.Principal
public import MinimalPrimes.AssociatedRestrictScalars
public import Mathlib.RingTheory.Spectrum.Prime.RingHom
import Mathlib.RingTheory.UniqueFactorizationDomain.GCDMonoid
import Mathlib.RingTheory.Coprime.Lemmas

/-!
# Associated primes of a principal quotient

The associated primes of a principal quotient, as ideals of the base ring, are
the minimal primes above the defining ideal in a unique factorization ring.
No choice of normalized factors is needed in the statement, including when the
generator is zero.

Mathlib defines associated primes using radicals of element annihilators. The
base-ring comparison does not identify ideals of the base ring with ideals of
the quotient; the pointwise comparisons use the quotient-spectrum order
isomorphism and also treat exact quotient-ring annihilators.

## References

* Ravi Vakil, *The Rising Sea: Foundations of Algebraic Geometry*, Exercise 6.6.F
  (motivation for the principal-quotient example).
* Mathlib's associated-prime and minimal-prime APIs, and the existing
  `MinimalPrimes.Principal` classification of principal ideals.
-/

set_option autoImplicit false
set_option relaxedAutoImplicit false
set_option linter.mathlibStandardSet true
set_option linter.style.header false

@[expose] public section

universe u

namespace Ideal

private theorem mem_radical_colon_mk_iff {R : Type u} [CommRing R]
    (generator witness scalar : R) :
    scalar ∈ ((⊥ : Submodule R (R ⧸ span {generator})).colon
      {Ideal.Quotient.mk (span {generator}) witness}).radical ↔
      ∃ exponent : ℕ, generator ∣ scalar ^ exponent * witness := by
  rw [Ideal.mem_radical_iff]
  simp only [Submodule.mem_colon_singleton, Submodule.mem_bot, Algebra.smul_def,
    Ideal.Quotient.algebraMap_eq, ← map_mul, Ideal.Quotient.eq_zero_iff_mem,
    Ideal.mem_span_singleton]

/-- The annihilator of the class of `witness` in `R/(factor * witness)` is
the principal ideal generated by `factor`, when `witness` is nonzero. -/
theorem colon_quotient_mk_mul_eq_span_singleton
    {R : Type u} [CommRing R] [IsCancelMulZero R]
    (factor witness : R) (hWitness : witness ≠ 0) :
    (⊥ : Submodule R (R ⧸ span {factor * witness})).colon
      {Ideal.Quotient.mk (span {factor * witness}) witness} = span {factor} := by
  ext scalar
  rw [Submodule.mem_colon_singleton, Submodule.mem_bot, Algebra.smul_def,
    Ideal.Quotient.algebraMap_eq, ← map_mul, Ideal.Quotient.eq_zero_iff_mem,
    Ideal.mem_span_singleton, mul_comm factor witness, mul_comm scalar witness,
    mul_dvd_mul_iff_left hWitness, Ideal.mem_span_singleton]

private theorem associatedPrimes_quotient_span_singleton_eq_minimalPrimes_of_ne_zero
    {R : Type u} [CommRing R] [UniqueFactorizationMonoid R] (f : R) (hf : f ≠ 0) :
    associatedPrimes R (R ⧸ span {f}) = (span {f}).minimalPrimes := by
  let : StrongNormalizationMonoid R := UniqueFactorizationMonoid.strongNormalizationMonoid
  ext primeIdeal
  constructor
  · intro hAssociated
    have : primeIdeal.IsPrime := hAssociated.isPrime
    have hGenerator : span {f} ≤ primeIdeal := by
      have hAnnihilator := hAssociated.annihilator_le
      rw [Submodule.annihilator_top, Ideal.annihilator_quotient] at hAnnihilator
      exact hAnnihilator
    obtain ⟨minimalIdeal, hMinimal, hBelow⟩ :=
      Ideal.exists_minimalPrimes_le hGenerator
    have hFactor := hMinimal
    rw [minimalPrimes_span_singleton_eq_normalizedFactors hf] at hFactor
    obtain ⟨primeFactor, hFactorMem, rfl⟩ := hFactor
    have hPrimeFactor : Prime primeFactor :=
      UniqueFactorizationMonoid.prime_of_normalized_factor primeFactor hFactorMem
    obtain ⟨witness, hWitness⟩ := hAssociated.2
    obtain ⟨witness, rfl⟩ :=
      Ideal.Quotient.mkₐ_surjective R (span {f}) witness
    simp only [Ideal.Quotient.mkₐ_eq_mk] at hWitness
    have hNotDivides : ¬ f ∣ witness := by
      intro hDivides
      have hOne : (1 : R) ∈ primeIdeal := by
        rw [hWitness, mem_radical_colon_mk_iff]
        exact ⟨0, by simpa using hDivides⟩
      exact hAssociated.isPrime.ne_top ((eq_top_iff_one primeIdeal).mpr hOne)
    have hPrimeMem : primeFactor ∈ primeIdeal :=
      hBelow (mem_span_singleton_self primeFactor)
    obtain ⟨primePower, hPrimePower⟩ :=
      (mem_radical_colon_mk_iff f witness primeFactor).mp (hWitness ▸ hPrimeMem)
    have hReverse : primeIdeal ≤ span {primeFactor} := by
      intro scalar hScalar
      by_contra hNotMem
      have hNotDividesPrime : ¬primeFactor ∣ scalar := by
        simpa only [mem_span_singleton] using hNotMem
      have hRelPrime : IsRelPrime primeFactor scalar :=
        hPrimeFactor.irreducible.isRelPrime_iff_not_dvd.mpr hNotDividesPrime
      obtain ⟨scalarPower, hScalarPower⟩ :=
        (mem_radical_colon_mk_iff f witness scalar).mp (hWitness ▸ hScalar)
      let : GCDMonoid R := UniqueFactorizationMonoid.toGCDMonoid R
      have hUnit : IsUnit (gcd (primeFactor ^ primePower) (scalar ^ scalarPower)) :=
        gcd_isUnit_iff_isRelPrime.mpr hRelPrime.pow
      have hDivides : f ∣ witness := by
        calc
          f ∣ gcd (primeFactor ^ primePower * witness)
              (scalar ^ scalarPower * witness) := dvd_gcd hPrimePower hScalarPower
          _ ∣ gcd (primeFactor ^ primePower) (scalar ^ scalarPower) * witness :=
            (gcd_mul_right' witness _ _).dvd
          _ ∣ witness := by
            simpa using (mul_dvd_mul_right (isUnit_iff_dvd_one.mp hUnit) witness)
      exact hNotDivides hDivides
    have hEqual : primeIdeal = span {primeFactor} := le_antisymm hReverse hBelow
    rw [hEqual]
    exact hMinimal
  · intro hMinimal
    have hFactor := hMinimal
    rw [minimalPrimes_span_singleton_eq_normalizedFactors hf] at hFactor
    obtain ⟨primeFactor, hFactorMem, rfl⟩ := hFactor
    have hPrimeFactor : (span {primeFactor} : Ideal R).IsPrime :=
      isPrime_span_singleton_of_prime
        (UniqueFactorizationMonoid.prime_of_normalized_factor primeFactor hFactorMem)
    obtain ⟨witness, hFactorization⟩ :=
      UniqueFactorizationMonoid.dvd_of_mem_normalizedFactors hFactorMem
    have hWitnessNonzero : witness ≠ 0 := by
      intro hZero
      apply hf
      rw [hFactorization, hZero, mul_zero]
    rw [hFactorization]
    exact ⟨hPrimeFactor, ⟨Ideal.Quotient.mk (span {primeFactor * witness}) witness,
      by rw [colon_quotient_mk_mul_eq_span_singleton primeFactor witness hWitnessNonzero,
        hPrimeFactor.radical]⟩⟩

/-- The associated primes of `R/(f)` as an `R`-module are exactly the minimal
primes above `(f)` in a unique factorization ring. Unlike a classification by
prime factors, this also includes the case `f = 0`. Mathlib's associated primes
are defined using radicals of annihilators, rather than requiring an exact
prime annihilator. Vakil's Exercise 6.6.F motivates the principal-quotient case;
the comparison uses Mathlib's associated-prime API and the existing principal-
ideal classification in `MinimalPrimes.Principal`. -/
theorem associatedPrimes_quotient_span_singleton_eq_minimalPrimes
    {R : Type u} [CommRing R] [UniqueFactorizationMonoid R] (f : R) :
    associatedPrimes R (R ⧸ Ideal.span {f}) = (Ideal.span {f}).minimalPrimes := by
  by_cases hTrivial : Subsingleton R
  · let : Subsingleton R := hTrivial
    have hTop : span {f} = (⊤ : Ideal R) := by
      rw [show f = 1 from Subsingleton.elim f 1]
      simp
    rw [associatedPrimes.eq_empty_of_subsingleton, hTop, minimalPrimes_top]
  · let : Nontrivial R := not_subsingleton_iff_nontrivial.mp hTrivial
    let : IsDomain R := {}
    by_cases hZero : f = 0
    · subst f
      have hPrime : (span {(0 : R)} : Ideal R).IsPrime := by
        simpa using (inferInstance : (⊥ : Ideal R).IsPrime)
      have hAssociated : associatedPrimes R (R ⧸ span {(0 : R)}) =
          {span {(0 : R)}} := by
        ext primeIdeal
        constructor
        · intro hMem
          exact (IsAssociatedPrime.eq_radical hPrime.isPrimary hMem).trans hPrime.radical
        · intro hMem
          have hEqual : primeIdeal = span {(0 : R)} := Set.mem_singleton_iff.mp hMem
          subst primeIdeal
          have hColon := colon_quotient_mk_mul_eq_span_singleton (0 : R) (1 : R) one_ne_zero
          rw [mul_one] at hColon
          exact ⟨hPrime, ⟨Ideal.Quotient.mk (span {(0 : R)}) 1,
            by rw [hColon, hPrime.radical]⟩⟩
      exact hAssociated.trans minimalPrimes_eq_subsingleton_self.symm
    · exact associatedPrimes_quotient_span_singleton_eq_minimalPrimes_of_ne_zero f hZero

/-- A point of the spectrum of a principal quotient is associated over the
quotient ring exactly when its image in the base spectrum is minimal above
the defining ideal. The spectrum correspondence maps forward by ideal comap. -/
theorem isAssociatedPrime_quotient_iff_minimalPrimes
    {R : Type u} [CommRing R] [UniqueFactorizationMonoid R]
    (f : R) (x : PrimeSpectrum (R ⧸ span {f})) :
    x.asIdeal ∈ associatedPrimes (R ⧸ span {f}) (R ⧸ span {f}) ↔
      ((Ideal.span {f}).primeSpectrumQuotientOrderIsoZeroLocus x).1.asIdeal ∈
        (span {f}).minimalPrimes := by
  rw [← associatedPrimes_quotient_span_singleton_eq_minimalPrimes f]
  change IsAssociatedPrime x.asIdeal (R ⧸ span {f}) ↔
    IsAssociatedPrime (x.asIdeal.comap (Ideal.Quotient.mk (span {f})))
      (R ⧸ span {f})
  exact (IsAssociatedPrime.comap_algebraMap_iff (R := R)
    (M := R ⧸ span {f}) x.asIdeal
    (by simpa only [Ideal.Quotient.algebraMap_eq] using
      (Ideal.Quotient.mk_surjective :
        Function.Surjective (Ideal.Quotient.mk (span {f})) ))).symm

private theorem eq_colon_quotient_of_comap_eq
    {R : Type u} [CommRing R] (I : Ideal R) (x : PrimeSpectrum (R ⧸ I)) (witness : R)
    (hComap : x.asIdeal.comap (Ideal.Quotient.mk I) =
      (⊥ : Submodule R (R ⧸ I)).colon {Ideal.Quotient.mk I witness}) :
    x.asIdeal = (⊥ : Submodule (R ⧸ I) (R ⧸ I)).colon
      {Ideal.Quotient.mk I witness} := by
  apply Ideal.comap_injective_of_surjective
    (Ideal.Quotient.mk I) Ideal.Quotient.mk_surjective
  rw [← Ideal.Quotient.algebraMap_eq I]
  rw [← Submodule.colon_restrictScalars (R := R), Submodule.restrictScalars_bot,
    Ideal.Quotient.algebraMap_eq I]
  exact hComap

/-- A point of a principal-quotient spectrum has an exact element annihilator
in the quotient ring exactly when its image is minimal above the defining
ideal in a unique factorization ring. -/
theorem exists_colon_quotient_iff_minimalPrimes
    {R : Type u} [CommRing R] [UniqueFactorizationMonoid R]
    (f : R) (x : PrimeSpectrum (R ⧸ span {f})) :
    (∃ witness : R ⧸ span {f}, x.asIdeal =
      (⊥ : Submodule (R ⧸ span {f}) (R ⧸ span {f})).colon {witness}) ↔
      ((Ideal.span {f}).primeSpectrumQuotientOrderIsoZeroLocus x).1.asIdeal ∈
        (span {f}).minimalPrimes := by
  constructor
  · rintro ⟨witness, hExact⟩
    apply (isAssociatedPrime_quotient_iff_minimalPrimes f x).mp
    refine ⟨x.isPrime, witness, ?_⟩
    rw [← hExact]
    exact x.isPrime.radical.symm
  · intro hMinimal
    by_cases hTrivial : Subsingleton R
    · let : Subsingleton R := hTrivial
      have hTop : span {f} = (⊤ : Ideal R) := by
        rw [show f = 1 from Subsingleton.elim f 1]
        simp
      have hEmpty : (span {f}).minimalPrimes = ∅ := by
        rw [hTop, minimalPrimes_top]
      rw [hEmpty] at hMinimal
      exact False.elim hMinimal
    · let : Nontrivial R := not_subsingleton_iff_nontrivial.mp hTrivial
      let : IsDomain R := {}
      by_cases hZero : f = 0
      · subst f
        have hPrime : (span {(0 : R)} : Ideal R).IsPrime := by
          simpa using (inferInstance : (⊥ : Ideal R).IsPrime)
        have hAssociated : IsAssociatedPrime
            ((span {(0 : R)}).primeSpectrumQuotientOrderIsoZeroLocus x).1.asIdeal
            (R ⧸ span {(0 : R)}) := by
          rw [← associatedPrimes_quotient_span_singleton_eq_minimalPrimes (0 : R)]
            at hMinimal
          exact hMinimal
        have hPoint : x.asIdeal.comap (Ideal.Quotient.mk (span {(0 : R)})) =
            span {(0 : R)} := by
          change ((span {(0 : R)}).primeSpectrumQuotientOrderIsoZeroLocus x).1.asIdeal =
            span {(0 : R)}
          exact (IsAssociatedPrime.eq_radical hPrime.isPrimary hAssociated).trans
            hPrime.radical
        have hColon := colon_quotient_mk_mul_eq_span_singleton
          (0 : R) (1 : R) one_ne_zero
        rw [mul_one] at hColon
        exact ⟨Ideal.Quotient.mk (span {(0 : R)}) 1,
          eq_colon_quotient_of_comap_eq _ x 1 (hPoint.trans hColon.symm)⟩
      · let : StrongNormalizationMonoid R :=
          UniqueFactorizationMonoid.strongNormalizationMonoid
        have hFactor := hMinimal
        rw [minimalPrimes_span_singleton_eq_normalizedFactors hZero] at hFactor
        obtain ⟨primeFactor, hFactorMem, hPoint⟩ := hFactor
        obtain ⟨witness, hFactorization⟩ :=
          UniqueFactorizationMonoid.dvd_of_mem_normalizedFactors hFactorMem
        have hWitnessNonzero : witness ≠ 0 := by
          intro hWitnessZero
          apply hZero
          rw [hFactorization, hWitnessZero, mul_zero]
        have hColon : (⊥ : Submodule R (R ⧸ span {f})).colon
            {Ideal.Quotient.mk (span {f}) witness} = span {primeFactor} := by
          rw [hFactorization]
          exact colon_quotient_mk_mul_eq_span_singleton primeFactor witness hWitnessNonzero
        have hPointComap : x.asIdeal.comap (Ideal.Quotient.mk (span {f})) =
            span {primeFactor} := hPoint
        exact ⟨Ideal.Quotient.mk (span {f}) witness,
          eq_colon_quotient_of_comap_eq _ x witness (hPointComap.trans hColon.symm)⟩

end Ideal
