/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import Mathlib.RingTheory.Ideal.MinimalPrime.Basic
public import Mathlib.RingTheory.UniqueFactorizationDomain.NormalizedFactors

/-!
# Minimal primes over a principal ideal in a UFD

This file classifies the minimal primes over a nonzero principal ideal in a
commutative unique factorization domain. The classification uses membership in
the multiset of normalized factors, and therefore deliberately forgets factor
multiplicity. The caller supplies a `NormalizationMonoid` instance, so the factors
in the results use the caller's chosen normalized representatives. All results
assume the element is nonzero; units have no factors or minimal primes above
their principal ideal.
-/

@[expose] public section

noncomputable section

open UniqueFactorizationMonoid

universe u

namespace Ideal

variable {R : Type u} [CommRing R] [UniqueFactorizationMonoid R]
  [NormalizationMonoid R]

/-- The minimal primes over a nonzero principal ideal in a commutative UFD are
the principal ideals generated by the normalized irreducible factors.

Membership in `normalizedFactors f` is a proposition about a multiset, so this
set equality intentionally forgets the multiplicity of repeated factors.
The proof factors `f` up to association, uses primality to select a factor of
the product, and uses minimality in both directions. The nonzero assumption
excludes zero, whose empty factor multiset does not classify `(0)`. -/
theorem minimalPrimes_span_singleton_eq_normalizedFactors {f : R} (hf : f ≠ 0) :
    (span {f}).minimalPrimes =
      {P | ∃ p ∈ normalizedFactors f, P = span {p}} := by
  ext P
  constructor
  · intro hP
    have hfP : f ∈ P := hP.le (mem_span_singleton_self f)
    have hprodP : (normalizedFactors f).prod ∈ P :=
      (mem_iff_of_associated
        (UniqueFactorizationMonoid.prod_normalizedFactors hf)).mpr hfP
    obtain ⟨p, hpf, hpP⟩ :=
      hP.isPrime.multiset_prod_mem_iff_exists_mem (normalizedFactors f) |>.mp hprodP
    have hpPrime : (span {p} : Ideal R).IsPrime :=
      isPrime_span_singleton_of_prime
        (UniqueFactorizationMonoid.prime_of_normalized_factor p hpf)
    have hfspan : span {f} ≤ span {p} := by
      rw [span_singleton_le_iff_mem, mem_span_singleton]
      exact UniqueFactorizationMonoid.dvd_of_mem_normalizedFactors hpf
    have hspanP : span {p} ≤ P :=
      (span_singleton_le_iff_mem (I := P)).mpr hpP
    exact ⟨p, hpf, le_antisymm (hP.2 ⟨hpPrime, hfspan⟩ hspanP) hspanP⟩
  · rintro ⟨p, hpf, rfl⟩
    have hpPrime : (span {p} : Ideal R).IsPrime :=
      isPrime_span_singleton_of_prime
        (UniqueFactorizationMonoid.prime_of_normalized_factor p hpf)
    have hfspan : span {f} ≤ span {p} := by
      rw [span_singleton_le_iff_mem, mem_span_singleton]
      exact UniqueFactorizationMonoid.dvd_of_mem_normalizedFactors hpf
    refine ⟨⟨hpPrime, hfspan⟩, ?_⟩
    intro Q hQ hQle
    have hfQ : f ∈ Q := hQ.2 (mem_span_singleton_self f)
    have hprodQ : (normalizedFactors f).prod ∈ Q :=
      (mem_iff_of_associated
        (UniqueFactorizationMonoid.prod_normalizedFactors hf)).mpr hfQ
    obtain ⟨q, hqf, hqQ⟩ :=
      hQ.1.multiset_prod_mem_iff_exists_mem (normalizedFactors f) |>.mp hprodQ
    have hspanqQ : span {q} ≤ Q :=
      (span_singleton_le_iff_mem (I := Q)).mpr hqQ
    have hp_dvd_q : p ∣ q := mem_span_singleton.mp <|
      hQle (hspanqQ (mem_span_singleton_self q))
    have hpq : p = q :=
      UniqueFactorizationMonoid.normalizedFactors_eq_of_dvd f p hpf q hqf hp_dvd_q
    simpa [hpq] using hspanqQ

/-- The normalized factor *values* of a nonzero element are equivalent to the
minimal primes over its principal ideal. The forward map sends a factor to its
principal ideal; `Equiv.ofBijective` selects the inverse noncomputably. Repeated
occurrences of a factor are not separate elements of the subtype. -/
def normalizedFactorsEquivMinimalPrimes {f : R} (hf : f ≠ 0) :
    {p // p ∈ normalizedFactors f} ≃ (span {f}).minimalPrimes := by
  exact Equiv.ofBijective
    (fun p ↦ ⟨span {p.1}, by
      rw [minimalPrimes_span_singleton_eq_normalizedFactors hf]
      exact ⟨p.1, p.2, rfl⟩⟩)
    ⟨by
      intro p q hpq
      apply Subtype.ext
      apply UniqueFactorizationMonoid.mem_normalizedFactors_eq_of_associated p.2 q.2
      have hspan : span {p.1} = span {q.1} := congrArg Subtype.val hpq
      apply dvd_dvd_iff_associated.mp
      constructor
      · apply mem_span_singleton.mp
        rw [hspan]
        exact mem_span_singleton_self q.1
      · apply mem_span_singleton.mp
        rw [← hspan]
        exact mem_span_singleton_self p.1,
    by
      intro P
      have hP : ∃ p ∈ normalizedFactors f, P.1 = span {p} := by
        have hm := congrArg (fun s : Set (Ideal R) ↦ P.1 ∈ s)
          (minimalPrimes_span_singleton_eq_normalizedFactors hf)
        exact (Iff.of_eq hm).mp P.2
      obtain ⟨p, hpf, hpP⟩ := hP
      refine ⟨⟨p, hpf⟩, ?_⟩
      apply Subtype.ext
      exact hpP.symm⟩

/-- The factor-to-minimal-prime equivalence sends a normalized factor to its
principal ideal. This forward-map equality holds by `rfl` and is a simp lemma. -/
@[simp]
theorem normalizedFactorsEquivMinimalPrimes_apply {f : R} (hf : f ≠ 0)
    (p : {p // p ∈ normalizedFactors f}) :
    (normalizedFactorsEquivMinimalPrimes hf p).1 = span {p.1} :=
  rfl

end Ideal
